### ISSUE TITLE
Fix various md files

### ISSUE THREAD

**Issue by aaronhsli** [amosyu2000/cyclops#158]
![image](https://user-images.githubusercontent.com/58313755/201269279-d903bfbf-e8b6-4464-969d-1fe4f31b6cf9.png)

Code of Conduct does not have a contact name.

**Comment by amosyu2000** [comment]
Also need to remove line 1 from the license file 
![image](https://user-images.githubusercontent.com/46848538/201370461-a07f7d3b-2ddc-4634-b639-8fcfd2e2dace.png)

**Comment by amosyu2000** [comment]
Also need to update the refs/README.md file 
![image](https://user-images.githubusercontent.com/46848538/201371099-547e1381-2944-4895-b77c-645c4b2ba174.png)

**Comment by amosyu2000** [comment]
README titles should be centered. 
![image](https://user-images.githubusercontent.com/46848538/201371694-5bbcde55-7d79-466e-95d0-38ba43456cd6.png)
