### ISSUE TITLE
MIS: Add software specifications, electrical, mechanical info

### ISSUE THREAD

**Issue by aaronhsli** [amosyu2000/cyclops#186]

**Comment by aaronhsli** [comment]
![image](https://user-images.githubusercontent.com/58313755/213242698-29e0ad61-2088-429e-91e5-0e97043f7a81.png)

**Comment by aaronhsli** [comment]
[RaspberryPi4ElectricalSchematic.pdf](https://github.com/amosyu2000/cyclops/files/10448801/RaspberryPi4ElectricalSchematic.pdf)

**Comment by aaronhsli** [comment]
![RaspberryPi4ElectricalSchematic](https://user-images.githubusercontent.com/58313755/213247210-1cf36f4d-d1d2-463e-be8d-ee6f19534f09.png)

**Comment by aaronhsli** [comment]
![image](https://user-images.githubusercontent.com/58313755/213313332-c1c2251d-6979-4156-905c-64cfcd728fba.png)

**Comment by aaronhsli** [comment]
![image](https://user-images.githubusercontent.com/58313755/213313607-af71d40e-9ca5-408c-966d-48411e60234f.png)

**Comment by aaronhsli** [comment]
![image](https://user-images.githubusercontent.com/58313755/213313743-9a756f6c-f0cb-4c9f-b2b1-f3c17105ddc7.png)

**Comment by amosyu2000** [comment]
![image](https://user-images.githubusercontent.com/46848538/213317988-3e1dbebb-54af-4f58-bcc3-202ff45de1c2.png)

**Comment by amosyu2000** [comment]
![image](https://user-images.githubusercontent.com/46848538/213323584-7ad14da3-8865-4878-8e06-ba42eb49f347.png)

**Comment by amosyu2000** [comment]
![image](https://user-images.githubusercontent.com/46848538/213323907-9c962406-62c2-4108-8010-261398c026c2.png)

**Comment by aaronhsli** [comment]
![image](https://user-images.githubusercontent.com/58313755/213337993-6efc55c0-f281-432d-bbbd-4ff78e75fa65.png)

**Comment by aaronhsli** [comment]
![image](https://user-images.githubusercontent.com/58313755/213338155-603d739b-801f-4f6a-b7a0-1c20f1802983.png)

**Comment by aaronhsli** [comment]
![image](https://user-images.githubusercontent.com/58313755/213349323-a8a92c4f-437d-4670-a278-7c6d454ea6a5.png)

**Comment by aaronhsli** [comment]
![image](https://user-images.githubusercontent.com/58313755/213349398-fab2ee2d-e341-401e-9c1f-e161055ec47c.png)
