### ISSUE TITLE
Team04 DD Review: Project Overview

### ISSUE THREAD

**Issue by jtgc1** [amosyu2000/cyclops#216]
The project overview section lacks context and connection to the requirements of the project. Your diagram is very nice with the classification of systems and detailing what is contained in the connection between subsystems. However, there is no information about what requirements were considered when making the design decisions.

**Comment by amoscheung99527** [comment]
In later on of the MIS we addressed each module and what requirements they fulfill, so we are not going to add it in the project overview.
