### ISSUE TITLE
Team04 DD Review: Module Guide

### ISSUE THREAD

**Issue by jtgc1** [amosyu2000/cyclops#220]
The lack of a module guide in the document is felt by the lack of connection between sections. A module guide would work nicely to connect the design sections with the electrical components with the module descriptions. The module guide is also useful for displaying module hierarchy and connection to the requirements.

**Comment by amoscheung99527** [comment]
![image](https://user-images.githubusercontent.com/47584370/216482302-8ad78f07-3834-49dd-a846-d0c5b37750f9.png)
