### ISSUE TITLE
Final Demo (April 1st, 4:00PM)

### ISSUE THREAD

**Issue by amosyu2000** [amosyu2000/cyclops#269]
![image](https://user-images.githubusercontent.com/46848538/223166964-d76776af-a216-4225-94b7-872063665936.png)

![image](https://user-images.githubusercontent.com/46848538/223166874-fa0e49b9-a7b0-40c5-aa95-5603407574e7.png)

**Comment by aaronhsli** [comment]
ITB 137

**Comment by amosyu2000** [comment]
> ITB 137

i know it says in the screenshot
