### ISSUE TITLE
Team3 Review: Code Coverage Missing Documentation on Procedure 

### ISSUE THREAD

**Issue by arkinmodi** [amosyu2000/cyclops#279]
You code coverage does not have any supporting documentation on how coverage was collected. You state that majority of your testing is manual with "limited" use of automated testing (i.e., pytest), however we are not sure how you have collected these metrics. 

Additionally, you have only 1 automated test.

https://github.com/amosyu2000/cyclops/blob/add511989aa270995d1324bf90db497060715690/test/acceleration_test.py#L9-L17

TAs: @NickCapstone @tomashetMcMaster

**Comment by briantule** [comment]
1. Details regarding how coverage was collected has been added to section description.
2. Automated tests have been made for sections that are able to be automated. The majority of the system requires for CRA to be actively running which is difficult and sometimes not practical for automated testing. This is why we introduced manual/real world testing suites to fill out the void and increase code coverage. Automated unit testings will be updated along with the continual changes made to source code within the upcoming days.
