### ISSUE TITLE
Team 34 VnVReport Review: Unit Tests

### ISSUE THREAD

**Issue by WinnieTrandinh** [amosyu2000/cyclops#284]
@NickCapstone 

Well done with creating unit tests for the various modules in the VnVReport.
However, some modules seem to be missing according to the MIS.
For example, Microcontroller System, Headlight System, and Blind Spot Monitoring modules does not have associated test cases within Section 6 of the VnVReport. 

All modules listed within the MIS should have unit tests for them, or have an explanation as to why there is none. If the modules have changed, the MIS should also be updated to reflect this change.

**Comment by amoscheung99527** [comment]
Blind spot detection has test cases under 6.1. Microcontroller and headlights does not need testing as they are already established products that was bought online
